import 'dart:convert';
import 'open_responses_models.dart';

/// Returns true if the JSON body is a valid Open Responses top-level response.
///
/// Detection heuristic:
///   - Must be a JSON object
///   - Must have an `output` key that is a list
///   - That list must contain at least one object with a `type` key
///     that is one of the known item types
bool isOpenResponsesJson(String? body) {
  if (body == null || body.isEmpty) return false;
  try {
    final decoded = jsonDecode(body);
    if (decoded is! Map<String, dynamic>) return false;
    final output = decoded['output'];
    if (output is! List || output.isEmpty) return false;
    const knownTypes = {
      'message',
      'reasoning',
      'function_call',
      'function_call_output',
    };
    return output.any((item) {
      if (item is! Map<String, dynamic>) return false;
      final type = item['type'];
      return type is String && knownTypes.contains(type);
    });
  } catch (_) {
    return false;
  }
}

/// Parse a validated Open Responses JSON body into a structured response.
/// Returns null if parsing fails.
OpenResponsesResponse? parseOpenResponsesBody(String body) {
  try {
    final decoded = jsonDecode(body);
    if (decoded is! Map<String, dynamic>) return null;
    return OpenResponsesResponse.fromJsonMap(decoded);
  } catch (_) {
    return null;
  }
}

/// Generate a Flutter code snippet a user can paste into their app
/// to render the same response.
String generateFlutterSnippet(String jsonBody) {
  const tq = "'''"; // Triple-quote delimiter — avoids escape lint warnings.
  return """
// ─────────────────────────────────────────────────────────────────────────────
// Generated by APIDash — Open Responses Visualizer
// Paste this into your Flutter project to render this LLM response.
//
// 1. Add the dependency to pubspec.yaml (when published):
//    open_responses_ui: ^0.1.0
//
// 2. Use the widget:
// ─────────────────────────────────────────────────────────────────────────────

import 'package:flutter/material.dart';

const String kResponseJson = r$tq
$jsonBody
$tq;

class MyResponseView extends StatelessWidget {
  const MyResponseView({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('AI Response')),
      body: OpenResponsesViewer(jsonBody: kResponseJson),
    );
  }
}
""";
}
